/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.projetounificadoMSPSC;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allan
 */
public class FormProjetoLista extends javax.swing.JFrame {
    public static Projeto projetoForm;
    
    public void recuperarListaProjeto() {
        Vector listaProjeto = projetoForm.recuperarListaProjetos();
        
        Vector nomesColunas = new Vector(); 
        nomesColunas.add("ID");
        nomesColunas.add("Nome");
        nomesColunas.add("Descrição");
        nomesColunas.add("Usuário Proprietário");
        
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(listaProjeto, nomesColunas);
                
        tblProjetos.setModel(dataModel);
    }
    /**
     * Creates new form FormProjetoLista
     */
    public FormProjetoLista() {
        initComponents();
        
        projetoForm = new Projeto();

        recuperarListaProjeto();
        
        btnSalvar.setVisible(false);
        btnCancel.setVisible(false);
    }
    
    public void getSelectedProject() {
        try {
            if (tblProjetos.getSelectedRow() != -1) {
                int idProjeto = tblProjetos.getValueAt(tblProjetos.getSelectedRow(), 0).hashCode();

                projetoForm.getDataProjects(idProjeto);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível resgatar o valor do ID!");
        }
    }
    
    public void atualizar() {
        String nomeProjeto = txtNomeProjeto.getText();
        String desc = txtDescricaoProjeto.getText();
        
        projetoForm.alterarDadosDoProjeto(nomeProjeto, desc);
        
        recuperarListaProjeto();
        
        JOptionPane.showMessageDialog(null, "Projeto alterado com sucesso!");
        
        tblProjetos.setEnabled(true);
        txtNomeProjeto.setEnabled(false);
        txtDescricaoProjeto.setEnabled(false);
        btnRemoverProjeto.setEnabled(true);
        btnVoltar.setEnabled(true);
        btnConsultarProjeto.setEnabled(true);
        btnAlterarProjeto.setEnabled(true);
        btnCancel.setVisible(false);
        btnSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjetos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnRemoverProjeto = new javax.swing.JButton();
        btnAlterarProjeto = new javax.swing.JButton();
        btnConsultarProjeto = new javax.swing.JButton();
        lblNomeProjeto = new javax.swing.JLabel();
        txtNomeProjeto = new javax.swing.JTextField();
        lblDescProjeto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoProjeto = new javax.swing.JTextArea();
        lblNomeProprietario = new javax.swing.JLabel();
        txtUsuarioProprietario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtExplicacao = new javax.swing.JTextArea();
        btnConsultarRequisitos = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Usuário Proprietário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProjetos);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnRemoverProjeto.setText("Remover Projeto");
        btnRemoverProjeto.setEnabled(false);
        btnRemoverProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProjetoActionPerformed(evt);
            }
        });

        btnAlterarProjeto.setText("Alterar Projeto");
        btnAlterarProjeto.setEnabled(false);
        btnAlterarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProjetoActionPerformed(evt);
            }
        });

        btnConsultarProjeto.setText("Consultar Projeto");
        btnConsultarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProjetoActionPerformed(evt);
            }
        });

        lblNomeProjeto.setText("Nome do Projeto:");

        txtNomeProjeto.setText("");
        txtNomeProjeto.setEnabled(false);

        lblDescProjeto.setText("Descrição do Projeto:");

        txtDescricaoProjeto.setColumns(20);
        txtDescricaoProjeto.setRows(5);
        txtDescricaoProjeto.setText("");
        txtDescricaoProjeto.setEnabled(false);
        jScrollPane2.setViewportView(txtDescricaoProjeto);

        lblNomeProprietario.setText("Nome do Usuário Proprietário:");

        txtUsuarioProprietario.setText("");
        txtUsuarioProprietario.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtExplicacao.setColumns(20);
        txtExplicacao.setRows(5);
        txtExplicacao.setText("Para obter e manipular os dados de\num projeto, basta selecionar o \ndesejado na lista e clicar em \n\"Consultar Projeto\".");
        txtExplicacao.setEnabled(false);
        jScrollPane3.setViewportView(txtExplicacao);

        btnConsultarRequisitos.setText("Consultar Requisitos");
        btnConsultarRequisitos.setEnabled(false);
        btnConsultarRequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRequisitosActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Gerar Relatório de Projetos");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAlterarProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultarProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarRequisitos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRelatorio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUsuarioProprietario)
                                        .addComponent(txtNomeProjeto)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNomeProprietario)
                                                .addComponent(lblNomeProjeto))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDescProjeto)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRemoverProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(318, 318, 318)
                                    .addComponent(btnVoltar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnRemoverProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarProjeto)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancel)
                    .addComponent(btnConsultarRequisitos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarProjeto)
                    .addComponent(btnRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProjeto)
                    .addComponent(lblDescProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lblNomeProprietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        FormMenuPrincipal menuPrincipal = new FormMenuPrincipal();
        menuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProjetoActionPerformed
        // TODO add your handling code here:
        if(tblProjetos.getSelectedRow() != -1) {
            getSelectedProject();
        
            txtNomeProjeto.setText(projetoForm.getNome());
            txtDescricaoProjeto.setText(projetoForm.getDescricao());
            txtUsuarioProprietario.setText(projetoForm.getUsuarioProprietario());
        
            boolean verificado = projetoForm.verificarUsuarioProprietario();
        
            if (verificado) {
                btnAlterarProjeto.setEnabled(true);
                btnRemoverProjeto.setEnabled(true);
            }
            else {
                btnAlterarProjeto.setEnabled(false);
                btnRemoverProjeto.setEnabled(false);
            }
        
            btnConsultarRequisitos.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarProjetoActionPerformed

    private void btnAlterarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProjetoActionPerformed
        // TODO add your handling code here:
        tblProjetos.setEnabled(false);
        txtNomeProjeto.setEnabled(true);
        txtDescricaoProjeto.setEnabled(true);
        btnRemoverProjeto.setEnabled(false);
        btnVoltar.setEnabled(false);
        btnConsultarProjeto.setEnabled(false);
        btnCancel.setVisible(true);
        btnSalvar.setVisible(true);
        btnConsultarRequisitos.setEnabled(false);
    }//GEN-LAST:event_btnAlterarProjetoActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        tblProjetos.setEnabled(true);
        txtNomeProjeto.setEnabled(false);
        txtDescricaoProjeto.setEnabled(false);
        btnRemoverProjeto.setEnabled(true);
        btnVoltar.setEnabled(true);
        btnConsultarProjeto.setEnabled(true);
        btnCancel.setVisible(false);
        btnSalvar.setVisible(false);
        btnConsultarRequisitos.setEnabled(true);
        btnRelatorio.setEnabled(true);
        
        txtNomeProjeto.setText(projetoForm.getNome());
        txtUsuarioProprietario.setText(projetoForm.getUsuarioProprietario());
        txtDescricaoProjeto.setText(projetoForm.getDescricao());
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeProjeto.getText();
        String desc = txtDescricaoProjeto.getText();
        
        boolean validado = projetoForm.autenticarProjeto(nome);
        
        if (txtNomeProjeto.getText().isEmpty() || txtDescricaoProjeto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para que o sistemas possa alterar seus dados!");
        }
        else {
            boolean mesmoNome = (projetoForm.getNome() == nome) ? true : false;
            
            if (mesmoNome) {
                atualizar();
                projetoForm.setNome(nome);
                projetoForm.setDescricao(desc);
                btnConsultarRequisitos.setEnabled(true);
                btnRelatorio.setEnabled(true);
            }
            else if (validado) {
                atualizar();
                projetoForm.setNome(nome);
                projetoForm.setDescricao(desc);
                btnConsultarRequisitos.setEnabled(true);
                btnRelatorio.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Já existe um projeto com esse nome cadastrado no sistema. Use um diferente!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProjetoActionPerformed
        // TODO add your handling code here:
        String alerta = "Tem certeza que deseja excluir esse projeto?\nTodos os requisitos contidos nele serão deletados também!";
        
        int confirm = JOptionPane.showConfirmDialog(null, alerta);
        
        if (confirm == JOptionPane.YES_OPTION) {
            btnAlterarProjeto.setEnabled(false);
            btnRemoverProjeto.setEnabled(false);
            
            txtDescricaoProjeto.setText("");
            txtNomeProjeto.setText("");
            txtUsuarioProprietario.setText("");
            
            projetoForm.setNome("");
            projetoForm.setDescricao("");
            projetoForm.setUsuarioProprietario("");
            
            projetoForm.deletarProjeto();
            
            projetoForm.setId(0);
            
            recuperarListaProjeto();
            
            btnConsultarRequisitos.setEnabled(false);
            btnRelatorio.setEnabled(false);
        }
        else if (confirm == JOptionPane.NO_OPTION) {}
    }//GEN-LAST:event_btnRemoverProjetoActionPerformed

    private void btnConsultarRequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRequisitosActionPerformed
        // TODO add your handling code here:
        FormRequisitosLista requisitosForm = new FormRequisitosLista();
        requisitosForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultarRequisitosActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        FormRelatorioProjetos relatorioForm = new FormRelatorioProjetos();
        relatorioForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProjeto;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConsultarProjeto;
    private javax.swing.JButton btnConsultarRequisitos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnRemoverProjeto;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDescProjeto;
    private javax.swing.JLabel lblNomeProjeto;
    private javax.swing.JLabel lblNomeProprietario;
    private javax.swing.JTable tblProjetos;
    private javax.swing.JTextArea txtDescricaoProjeto;
    private javax.swing.JTextArea txtExplicacao;
    private javax.swing.JTextField txtNomeProjeto;
    private javax.swing.JTextField txtUsuarioProprietario;
    // End of variables declaration//GEN-END:variables
}
