/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.projetounificadoMSPSC;

import javax.swing.JOptionPane;

/**
 *
 * @author allan
 */
public class FormMenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form FormMenuPrincipal
     */
    public void desabilitarCampos() {
        txtNomeCompleto.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
    }
    
    public void habilitarCampos() {
        txtNomeCompleto.setEnabled(true);
        txtEmail.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
    }
    
    public void desabilitarBotoes () {
        btnProjetos.setEnabled(false);
        btnSair.setEnabled(false);
        btnExcluirConta.setEnabled(false);
        btnAlterarCadastro.setEnabled(false);
    }
    
    public void habilitarBotoes () {
        btnProjetos.setEnabled(true);
        btnSair.setEnabled(true);
        btnExcluirConta.setEnabled(true);
        btnAlterarCadastro.setEnabled(true);
    }
    
    public void atualizar(String user, String pass) {
        String nomeComp = txtNomeCompleto.getText();
        String email = txtEmail.getText();
        String fone = txtTelefone.getText();
        int id = Integer.parseInt(txtIDUsuario.getText());
                
        try {
            FormLogin.userLogin.alterarDadosCadastrais(id, nomeComp, user, email, pass, fone);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Por algúm motivo, não foi possível gravar os dados alterados!");
        }
                
        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                
        habilitarBotoes();
        desabilitarCampos();
        btnSalvar.setVisible(false);
    }
    
    public FormMenuPrincipal() {
        initComponents();
        
        txtIDUsuario.setVisible(!txtIDUsuario.isVisible());
        
        btnSalvar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        txtNomeCompleto = new javax.swing.JTextField();
        lblNomeCompleto = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNomeCompleto1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblNomeCompleto2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnAlterarCadastro = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtIDUsuario = new javax.swing.JTextField();
        mbPrincipal = new javax.swing.JMenuBar();
        btnProjetos = new javax.swing.JMenu();
        miCriarProjeto = new javax.swing.JMenuItem();
        miListarProjetos = new javax.swing.JMenuItem();

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluirConta.setText("Excluir Conta");
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });

        txtNomeCompleto.setText(FormLogin.userLogin.getNomeCompleto());
        txtNomeCompleto.setEnabled(false);

        lblNomeCompleto.setText("Nome Completo:");

        lblEmail.setText("E-mail:");

        txtEmail.setText(FormLogin.userLogin.getEmail());
        txtEmail.setEnabled(false);

        lblNomeCompleto1.setText("Senha:");

        txtUsuario.setText(FormLogin.userLogin.getUsuario());
        txtUsuario.setEnabled(false);

        lblNomeCompleto2.setText("Nome de Usuário:");

        txtSenha.setText(FormLogin.userLogin.getSenha());
        txtSenha.setEnabled(false);

        lblTelefone.setText("Telefone:");

        txtTelefone.setText(FormLogin.userLogin.getTelefone());
        txtTelefone.setEnabled(false);

        btnAlterarCadastro.setText("Alterar Cadastro");
        btnAlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCadastroActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtIDUsuario.setText(String.valueOf(FormLogin.userLogin.getId()));

        btnProjetos.setText("Projetos");

        miCriarProjeto.setText("Criar Projeto");
        miCriarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriarProjetoActionPerformed(evt);
            }
        });
        btnProjetos.add(miCriarProjeto);

        miListarProjetos.setText("Listar Projetos");
        miListarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarProjetosActionPerformed(evt);
            }
        });
        btnProjetos.add(miListarProjetos);

        mbPrincipal.add(btnProjetos);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirConta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCompleto2)
                            .addComponent(lblNomeCompleto1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeCompleto)
                        .addGap(7, 7, 7)
                        .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeCompleto2)
                        .addGap(7, 7, 7)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblNomeCompleto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnExcluirConta)
                    .addComponent(btnAlterarCadastro)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        // TODO add your handling code here:
        String alerta = "Tem certeza que deseja excluir sua conta?\nTodos os projetos e requisitos"
                + " criados por você serão excluídos juntamente com a sua conta!";
        
        int confirm = JOptionPane.showConfirmDialog(null, alerta);
        
        if (confirm == JOptionPane.YES_OPTION) {
            FormLogin.userLogin.excluirConta();
            
            FormLogin login = new FormLogin();
            login.setVisible(true);
            this.setVisible(false);
        }
        else if (confirm == JOptionPane.NO_OPTION) {}
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCadastroActionPerformed
        // TODO add your handling code here:
        habilitarCampos();
        desabilitarBotoes();
        
        btnSalvar.setVisible(true);
    }//GEN-LAST:event_btnAlterarCadastroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String user = txtUsuario.getText();
        boolean validado = FormLogin.userLogin.validarUsuario(user);
        
        String pass = String.valueOf(txtSenha.getPassword());
        
        if (txtNomeCompleto.getText().isEmpty() || txtUsuario.getText().isEmpty() || txtEmail.getText().isEmpty() || 
            pass.isEmpty() || txtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para que o sistemas possa alterar seus dados!");
        }
        else {
            boolean mesmoNome = (FormLogin.userLogin.getUsuario().equals(user)) ? true : false;
            
            if (mesmoNome) {
                atualizar(user, pass);
            }
            else if (validado) {
                atualizar(user, pass);
            }
            else {
                JOptionPane.showMessageDialog(null, "Esse nome de usuário já existe no sistema. Use um diferente!");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void miCriarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriarProjetoActionPerformed
        // TODO add your handling code here:
        FormCadastroProjeto cadProjeto = new FormCadastroProjeto();
        cadProjeto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miCriarProjetoActionPerformed

    private void miListarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarProjetosActionPerformed
        // TODO add your handling code here:
        FormProjetoLista listaProjetos = new FormProjetoLista();
        listaProjetos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miListarProjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCadastro;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JMenu btnProjetos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblNomeCompleto1;
    private javax.swing.JLabel lblNomeCompleto2;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miCriarProjeto;
    private javax.swing.JMenuItem miListarProjetos;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
