/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.projeto.projetounificadoMSPSC;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allan
 */
public class FormRelatoriosRequisitos extends javax.swing.JFrame {

    /**
     * Creates new form FormRelatoriosRequisitos
     */
    
    public void recuperarRelatorioRequisitos() {
        Vector relatorioRequisitos = FormRequisitosLista.requisitoForm.recuperarRelatorioRequisitos();
        
        Vector nomesColunas = new Vector(); 
        nomesColunas.add("ID");
        nomesColunas.add("Identificador");
        nomesColunas.add("Nome");
        nomesColunas.add("Módulo");
        nomesColunas.add("Funcionalidades");
        nomesColunas.add("Prioridade");
        nomesColunas.add("Descrição");
        nomesColunas.add("Autor");
        
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(relatorioRequisitos, nomesColunas);
                
        tblRequisitos.setModel(dataModel);
    }
    
    public FormRelatoriosRequisitos() {
        initComponents();
        
        recuperarRelatorioRequisitos();
    }
    
    public ResultSet carregaTabela(String tipo, String arg) throws SQLException {
        String argumento = tipo + " " + "LIKE \"%" + arg + "%\"";
        
        String sql = "SELECT R.ID, R.Identificador, R.Nome, R.Modulo, R.Funcionalidades, R.Prioridade, R.Descricao, P.Nome AS Projeto, "
                   + "U.NomeUsuario AS Autor "
                   + "FROM Requisitos R "
                   + "LEFT JOIN Usuarios U ON (R.Autor = U.ID) "
                   + "LEFT JOIN Projetos P ON (R.Projeto = P.ID)"
                   + "WHERE " + argumento + " AND P.ID = " + FormProjetoLista.projetoForm.getId();
        
            ConnectionFactory conexaoBD = new ConnectionFactory();
            Connection conn = conexaoBD.getConnection();
        
            Statement stm = conn.createStatement();
            
            ResultSet resultado; 
            resultado = stm.executeQuery(sql);
            
            return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFiltro = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequisitos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identificador", "Nome", "Módulo", "Funcionalidades", "Prioridade", "Descrição", "Autor" }));

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tblRequisitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Identificador", "Nome", "Módulo", "Funcionalidades", "Prioridade", "Descrição", "Autor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRequisitos);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormRequisitosLista requisitoLista = new FormRequisitosLista();
        requisitoLista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        // TODO add your handling code here:
        String tipo = "";
        
        String escolha = cbFiltro.getSelectedItem().toString().trim();
        
        if (escolha.equals("Identificador")) {
            tipo = " " + "R.Identificador";
        }
        if (escolha.equals("Nome")) {
            tipo = " " + "R.Nome";
        }
        if (escolha.equals("Módulo")) {
            tipo = " " + "R.Modulo";
        }
        if (escolha.equals("Funcionalidades")) {
            tipo = " " + "R.Funcionalidades";
        }
        if (escolha.equals("Prioridade")) {
            tipo = " " + "R.Prioridade";
        }
        if (escolha.equals("Descrição")) {
            tipo = " " + "R.Descricao";
        }
        if (escolha.equals("Autor")) {
            tipo = " " + "Autor";
        }
        
        String arg = txtFiltro.getText();
        
        DefaultTableModel mp1 = (DefaultTableModel) tblRequisitos.getModel();
        
        int l = mp1.getRowCount();
        
        if(l>0) {
            while(l>0) {
                ((DefaultTableModel) tblRequisitos.getModel()).removeRow(l-1);
                l--;
            }
        }
        
        try {
            ResultSet rs = carregaTabela(tipo, arg);
            
            DefaultTableModel mp = (DefaultTableModel) tblRequisitos.getModel();
            
            while(rs.next()){
                String Coluna0 = rs.getString("R.ID").toString().trim();
                String Coluna1 = rs.getString("R.Identificador").toString().trim();
                String Coluna2 = rs.getString("R.Nome").toString().trim();
                String Coluna3 = rs.getString("R.Modulo").toString().trim();
                String Coluna4 = rs.getString("R.Funcionalidades").toString().trim();
                String Coluna5 = rs.getString("R.Prioridade").toString().trim();
                String Coluna6 = rs.getString("R.Descricao").toString().trim();
                String Coluna7 = rs.getString("Autor").toString().trim();
                
                mp.addRow(new String[]{Coluna0, Coluna1, Coluna2, Coluna3, Coluna4, Coluna5, Coluna6, Coluna7});
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher a coluna com os dados solicitados!");
        }
    }//GEN-LAST:event_txtFiltroKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRequisitos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
